//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LocalizedText", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 进出日期.
        /// </summary>
        internal static string AcessDate {
            get {
                return ResourceManager.GetString("AcessDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 允許移動材料.
        /// </summary>
        internal static string AllowedMaterial {
            get {
                return ResourceManager.GetString("AllowedMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 允許攜帶手機.
        /// </summary>
        internal static string AllowedMoblie {
            get {
                return ResourceManager.GetString("AllowedMoblie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 允許攜帶电脑.
        /// </summary>
        internal static string AllowedNotebook {
            get {
                return ResourceManager.GetString("AllowedNotebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 允許拍照.
        /// </summary>
        internal static string AllowedPhoto {
            get {
                return ResourceManager.GetString("AllowedPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 允許攜帶U盘.
        /// </summary>
        internal static string AllowedUSBDisk {
            get {
                return ResourceManager.GetString("AllowedUSBDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 允許進入.
        /// </summary>
        internal static string AllowEnter {
            get {
                return ResourceManager.GetString("AllowEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管制区名称.
        /// </summary>
        internal static string AreaName {
            get {
                return ResourceManager.GetString("AreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权限管理.
        /// </summary>
        internal static string AuthorizationManagement {
            get {
                return ResourceManager.GetString("AuthorizationManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 黑色专案.
        /// </summary>
        internal static string BlackProject {
            get {
                return ResourceManager.GetString("BlackProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BU/管制区.
        /// </summary>
        internal static string BUArea {
            get {
                return ResourceManager.GetString("BUArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卡号.
        /// </summary>
        internal static string CardNo {
            get {
                return ResourceManager.GetString("CardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卡号/工号/姓名.
        /// </summary>
        internal static string CENNo {
            get {
                return ResourceManager.GetString("CENNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部门.
        /// </summary>
        internal static string Dept {
            get {
                return ResourceManager.GetString("Dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工号.
        /// </summary>
        internal static string EmpNo {
            get {
                return ResourceManager.GetString("EmpNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有效.
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 职务.
        /// </summary>
        internal static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to region:&apos;west&apos;,title:&apos;菜單導航&apos;,split:true.
        /// </summary>
        internal static string MenuNavigator {
            get {
                return ResourceManager.GetString("MenuNavigator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓名.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人员信息.
        /// </summary>
        internal static string PersonInformation {
            get {
                return ResourceManager.GetString("PersonInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 報表管理.
        /// </summary>
        internal static string ReportManagement {
            get {
                return ResourceManager.GetString("ReportManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 车间门禁.
        /// </summary>
        internal static string WorkshopAccess {
            get {
                return ResourceManager.GetString("WorkshopAccess", resourceCulture);
            }
        }
    }
}
